window.ENV_CONFIG = {
  VITE_OPENAI_API_KEY: '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',
  VITE_ASSISTANT_ID: 'asst_KuUnwCYEPBsYMEm6I2OSuEIT'
};
